[app]
name = "backup"
title = "Backup"
description = "Back up all Cloud in a Bottle data to any Restic provider"
repo_url = "https://github.com/imbue-openhost/backup"
website_url = "https://github.com/imbue-openhost/backup"
docs_url = "https://github.com/imbue-openhost/backup#readme"
tags = ["backup", "data"]
categories = ["utility"]
