[app]
name = "minecraft"
title = "Minecraft"
description = "A self-hosted minecraft server runner"
repo_url = "https://github.com/imbue-openhost/bottled-minecraft"
website_url = "https://github.com/imbue-openhost/bottled-minecraft"
docs_url = "https://github.com/imbue-openhost/bottled-minecraft#readme"
tags = ["minecraft", "games"]
categories = ["entertainment"]
